name: Create Release
on:
  push:
    branches:
      - master
jobs:
  increment_version_number:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Increment version number
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          NEW_TAG=$(echo $LATEST_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "::set-output name=new_tag::$NEW_TAG"
          id: increment_version_number  
  create_release:
    runs-on: ubuntu-latest
    needs: increment_version_number
    
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.increment_version.outputs.new_tag }}
          release_name: Release ${{ needs.increment_version.outputs.new_tag }}
          draft: false
          prerelease: false
