- name: Create Release
  id: create_release
  needs: increment_version_number
  uses: actions/create-release@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag_name: ${{ needs.increment_version.outputs.new_tag }}
    release_name: Release ${{ needs.increment_version.outputs.new_tag }}
    draft: false
    prerelease: false